up

diff --git a/.github/workflows/linter.yaml b/.github/workflows/linter.yaml
--- a/.github/workflows/linter.yaml
+++ b/.github/workflows/linter.yaml
@@ -84,3 +84,11 @@ jobs:
           cat clang-tidy.out | sed -e 's/\x1b\[[0-9;]*m//g' >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
         shell: bash
+      - name: Generate Annotations
+        if: ${{ success() || failure() }}
+        run: |
+          echo "::error file={cvmfs/duplex_curl.h},line={11},title={error: included header curl.h is not used directly [misc-include-cleaner,-warnings-as-errors]}::{message text line 1 %0A line2 %0A line3}
+        shell: bash
+
+
+
